#pragma once
// CSharpWriter — Generates C# class declarations from DumpResult.
// Output format: Il2CppDumper-style C# classes with fields and methods.
#include "../ExportCore/IExporter/IExporter.h"
#include "../ExportCore/SectionSplitter/SectionSplitter.h"
#include "../../DumperCore/DumpResult.h"
#include <fstream>
#include <sstream>
#include <iomanip>

namespace omnibyte::dumper::writers {

class CSharpWriter : public export_core::IExporter {
public:
    std::string formatName() const override { return "csharp"; }
    std::string fileExtension() const override { return ".cs"; }
    std::string description() const override {
        return "C# class declarations (Il2CppDumper-style)";
    }

    bool exportToFile(const DumpResult& result,
                      const std::string& outputPath) const override {
        std::ofstream file(outputPath);
        if (!file.is_open()) return false;

        file << exportToString(result);
        return file.good();
    }

    std::string exportToString(const DumpResult& result) const override {
        std::ostringstream out;

        // Header comment
        out << "// Generated by OmniByte Dumper\n";
        out << "// Engine: " << result.engineName << " v" << result.detectedVersion << "\n";
        out << "// Types: " << result.typeTable.size() << "\n";
        out << "// Methods: " << result.methodTable.size() << "\n\n";

        // Using statements
        out << "using System;\n";
        out << "using System.Collections.Generic;\n\n";

        // Split by namespace
        auto sections = export_core::SectionSplitter::splitByNamespace(result);

        for (const auto& section : sections) {
            out << "namespace " << section.namespace_ << " {\n";

            for (const auto& type : section.types) {
                writeType(out, type, result);
            }

            out << "}\n\n";
        }

        return out.str();
    }

private:
    void writeType(std::ostringstream& out, const TypeEntry& type,
                   const DumpResult& result) const {
        // Class declaration
        out << "    public class " << sanitizeName(type.name);
        if (!type.parentType.empty()) {
            out << " : " << sanitizeName(type.parentType);
        }
        out << " {\n";

        // Fields sorted by offset
        auto fields = export_core::SectionSplitter::getFieldsForType(result, type.name);
        for (size_t i = 0; i < fields.size(); ++i) {
            writeField(out, fields[i], i);
        }

        // Methods
        auto methods = export_core::SectionSplitter::getMethodsForType(result, type.name);
        for (const auto& method : methods) {
            writeMethod(out, method);
        }

        out << "    }\n\n";
    }

    void writeField(std::ostringstream& out, const FieldEntry& field, size_t index) const {
        std::string csType = mapToCSharpType(field.typeName);
        out << "        public " << csType << " " << field.name;
        out << "; // 0x" << std::hex << std::setw(4) << std::setfill('0') << field.offset;
        out << "\n";
    }

    void writeMethod(std::ostringstream& out, const MethodEntry& method) const {
        out << "        ";
        if (method.isVirtual) out << "virtual ";
        if (method.isStatic) out << "static ";

        out << "void " << method.name << "() { }\n";
    }

    // Map native types to C# equivalents
    static std::string mapToCSharpType(const std::string& nativeType) {
        if (nativeType == "bool" || nativeType == "uint8_t") return "byte";
        if (nativeType == "int8_t") return "sbyte";
        if (nativeType == "int16_t") return "short";
        if (nativeType == "uint16_t") return "ushort";
        if (nativeType == "int32_t") return "int";
        if (nativeType == "uint32_t") return "uint";
        if (nativeType == "int64_t") return "long";
        if (nativeType == "uint64_t") return "ulong";
        if (nativeType == "float") return "float";
        if (nativeType == "double") return "double";
        if (nativeType == "void*") return "IntPtr";
        if (nativeType.find("char*") != std::string::npos) return "string";
        // Pointer types
        if (nativeType.find('*') != std::string::npos) return "IntPtr";
        return nativeType;
    }

    // Sanitize name for C# (remove dots, special chars)
    static std::string sanitizeName(const std::string& name) {
        std::string result;
        result.reserve(name.size());
        for (char c : name) {
            if (c == '.') result += '_';
            else if (std::isalnum(c) || c == '_') result += c;
        }
        return result;
    }
};

} // namespace omnibyte::dumper::writers
