#pragma once
// DummyDllWriter — Generates DummyDll-compatible C# assemblies from DumpResult.
// Output format: .NET-style C# classes for tools like RuntimeDumper.
#include "../../ExportCore/IExporter/IExporter.h"
#include "../../ExportCore/SectionSplitter/SectionSplitter.h"
#include "../../../DumperCore/DumpResult.h"
#include <fstream>
#include <sstream>
#include <map>

namespace omnibyte::dumper::writers {

class DummyDllWriter : public export_core::IExporter {
public:
    std::string formatName() const override { return "dummydll"; }
    std::string fileExtension() const override { return ".cs"; }
    std::string description() const override {
        return "DummyDll-compatible C# assemblies (for RuntimeDumper, etc.)";
    }

    bool exportToFile(const DumpResult& result,
                      const std::string& outputPath) const override {
        std::ofstream file(outputPath);
        if (!file.is_open()) return false;

        file << exportToString(result);
        return file.good();
    }

    std::string exportToString(const DumpResult& result) const override {
        std::ostringstream out;

        // Header
        out << "// Generated by OmniByte Dumper\n";
        out << "// Engine: " << result.engineName << " v" << result.detectedVersion << "\n";
        out << "// DummyDll-compatible output\n\n";

        // Group by assembly (based on namespace)
        std::map<std::string, std::vector<TypeEntry>> assemblies;
        for (const auto& type : result.typeTable) {
            std::string assembly = extractAssembly(type.name);
            assemblies[assembly].push_back(type);
        }

        for (const auto& [assembly, types] : assemblies) {
            out << "// Assembly: " << assembly << "\n";
            for (const auto& type : types) {
                writeType(out, type, result);
            }
            out << "\n";
        }

        return out.str();
    }

private:
    static std::string extractAssembly(const std::string& typeName) {
        auto dotPos = typeName.find('.');
        if (dotPos != std::string::npos) {
            return typeName.substr(0, dotPos);
        }
        return "Assembly-CSharp";
    }

    void writeType(std::ostringstream& out, const TypeEntry& type,
                   const DumpResult& result) const {
        // Determine if it's a class, struct, enum, or interface
        bool isInterface = type.name.find("I") == 0 && type.name.size() > 1 &&
                           std::isupper(type.name[1]);

        out << "namespace " << extractAssembly(type.name) << " {\n";
        if (isInterface) {
            out << "    public interface " << sanitizeName(type.name);
        } else {
            out << "    public class " << sanitizeName(type.name);
            if (!type.parentType.empty()) {
                out << " : " << sanitizeName(type.parentType);
            }
        }
        out << " {\n";

        // Fields
        auto fields = export_core::SectionSplitter::getFieldsForType(result, type.name);
        for (const auto& field : fields) {
            std::string csType = mapToCSharpType(field.typeName);
            out << "        public " << csType << " " << field.name << " { get; set; }\n";
        }

        // Methods
        auto methods = export_core::SectionSplitter::getMethodsForType(result, type.name);
        for (const auto& method : methods) {
            out << "        ";
            if (method.isVirtual) out << "virtual ";
            if (method.isStatic) out << "static ";
            out << "void " << method.name << "() { }\n";
        }

        out << "    }\n}\n\n";
    }

    static std::string mapToCSharpType(const std::string& nativeType) {
        if (nativeType == "bool" || nativeType == "uint8_t") return "byte";
        if (nativeType == "int8_t") return "sbyte";
        if (nativeType == "int16_t") return "short";
        if (nativeType == "uint16_t") return "ushort";
        if (nativeType == "int32_t") return "int";
        if (nativeType == "uint32_t") return "uint";
        if (nativeType == "int64_t") return "long";
        if (nativeType == "uint64_t") return "ulong";
        return "object";
    }

    static std::string sanitizeName(const std::string& name) {
        std::string result;
        for (char c : name) {
            if (std::isalnum(c) || c == '_') result += c;
            else if (c == '.') result += '_';
        }
        return result;
    }
};

} // namespace omnibyte::dumper::writers
