#pragma once
// Dumper1 DumpCsWriter — generates dump.cs (C# class stubs).
// Matches il2cpp-dumper output format: namespace/type hierarchy, fields with
// offset comments, methods with RVA placeholders.
#include "../../../DumperCore/DumpResult.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <map>

namespace omnibyte::dumper::dumper1 {

class DumpCsWriter {
public:
    // Generate dump.cs content from parsed DumpData.
    static std::string generate(const DumpData& data) {
        std::ostringstream out;

        out << "// Generated by OmniByte Dumper1\n";
        out << "// Engine: " << data.engineName << "\n";
        out << "// Types: " << data.typeTable.size() << "\n";
        out << "// Methods: " << data.methodTable.size() << "\n";
        out << "// Fields: " << data.fieldTable.size() << "\n\n";
        out << "using System;\n";
        out << "using System.Collections.Generic;\n\n";

        // Group types by namespace (split on last '.').
        std::map<std::string, std::vector<const TypeEntry*>> byNamespace;
        for (const auto& t : data.typeTable) {
            std::string ns = extractNamespace(t.name);
            byNamespace[ns].push_back(&t);
        }

        for (const auto& [ns, types] : byNamespace) {
            out << "namespace " << (ns.empty() ? "Global" : ns) << " {\n";
            for (const TypeEntry* t : types) {
                writeClass(out, *t, data);
            }
            out << "}\n\n";
        }

        return out.str();
    }

    // Write dump.cs to file.
    static bool writeFile(const DumpData& data, const std::string& path) {
        std::ofstream f(path);
        if (!f.is_open()) return false;
        f << generate(data);
        return f.good();
    }

private:
    // Extract namespace from fully-qualified name (e.g. "UnityEngine.GameObject" → "UnityEngine").
    static std::string extractNamespace(const std::string& fullName) {
        auto pos = fullName.rfind('.');
        return (pos != std::string::npos) ? fullName.substr(0, pos) : "";
    }

    // Extract short class name (e.g. "UnityEngine.GameObject" → "GameObject").
    static std::string extractClassName(const std::string& fullName) {
        auto pos = fullName.rfind('.');
        return (pos != std::string::npos) ? fullName.substr(pos + 1) : fullName;
    }

    // Sanitize identifier for C#.
    static std::string sanitize(const std::string& name) {
        std::string r;
        r.reserve(name.size());
        for (char c : name) {
            if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
                r += c;
            else
                r += '_';
        }
        return r;
    }

    static void writeClass(std::ostringstream& out, const TypeEntry& type,
                           const DumpData& data) {
        std::string clsName = sanitize(extractClassName(type.name));

        out << "    public class " << clsName;
        if (!type.parentType.empty()) {
            out << " : " << sanitize(extractClassName(type.parentType));
        }
        out << " {\n";

        // Fields grouped under this type.
        std::vector<const FieldEntry*> fields;
        for (const auto& f : data.fieldTable) {
            if (f.declaringType == type.name) {
                fields.push_back(&f);
            }
        }

        // Sort by offset.
        std::sort(fields.begin(), fields.end(),
                  [](const FieldEntry* a, const FieldEntry* b) {
                      return a->offset < b->offset;
                  });

        for (const FieldEntry* f : fields) {
            std::string csType = mapType(f->typeName);
            out << "        public " << csType << " " << sanitize(f->name);
            out << "; // 0x" << std::hex << std::setw(4) << std::setfill('0') << f->offset;
            out << std::dec << "\n";
        }

        // Methods grouped under this type.
        std::vector<const MethodEntry*> methods;
        for (const auto& m : data.methodTable) {
            if (m.declaringType == type.name) {
                methods.push_back(&m);
            }
        }

        for (const MethodEntry* m : methods) {
            out << "        public ";
            if (m->isStatic) out << "static ";
            if (m->isVirtual) out << "virtual ";
            out << "void " << sanitize(m->name) << "() { }\n";
        }

        out << "    }\n\n";
    }

    // Map IL2CPP type names to C# equivalents.
    static std::string mapType(const std::string& t) {
        if (t == "System.Boolean") return "bool";
        if (t == "System.Byte") return "byte";
        if (t == "System.SByte") return "sbyte";
        if (t == "System.Int16") return "short";
        if (t == "System.UInt16") return "ushort";
        if (t == "System.Int32") return "int";
        if (t == "System.UInt32") return "uint";
        if (t == "System.Int64") return "long";
        if (t == "System.UInt64") return "ulong";
        if (t == "System.Single") return "float";
        if (t == "System.Double") return "double";
        if (t == "System.String") return "string";
        if (t == "System.Void") return "void";
        if (t.empty()) return "object";
        return t;
    }
};

} // namespace omnibyte::dumper::dumper1
