#pragma once
// Dumper1 StaticFieldExporter — exports static field address/offset information.
// Produces a text report of all fields with their offsets, useful for runtime patching.
#include "../../Dumper/DumperCore/DumpResult.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <map>

namespace omnibyte::dumper::dumper1 {

class StaticFieldExporter {
public:
    // Generate static field report as string.
    static std::string generate(const DumpData& data) {
        std::ostringstream out;

        out << "// Generated by OmniByte Dumper1 — Static Field Offsets\n";
        out << "// Engine: " << data.engineName << "\n";
        out << "// Types: " << data.typeTable.size() << "\n";
        out << "// Fields: " << data.fieldTable.size() << "\n\n";

        // Group fields by declaring type.
        std::map<std::string, std::vector<const FieldEntry*>> byType;
        for (const auto& f : data.fieldTable) {
            byType[f.declaringType].push_back(&f);
        }

        // Column headers.
        out << "// Type                              Field Name              Offset    Size\n";
        out << "// ───────────────────────────────── ─────────────────────── ──────── ──────\n";

        for (const auto& [typeName, fields] : byType) {
            // Sort fields by offset.
            std::vector<const FieldEntry*> sorted = fields;
            std::sort(sorted.begin(), sorted.end(),
                      [](const FieldEntry* a, const FieldEntry* b) {
                          return a->offset < b->offset;
                      });

            for (const FieldEntry* f : sorted) {
                out << std::left;
                out << "  " << padRight(truncate(typeName, 33), 34);
                out << " " << padRight(truncate(f->name, 23), 24);
                out << " 0x" << std::hex << std::setw(8) << std::setfill('0') << f->offset;
                out << "  0x" << std::setw(4) << std::setfill('0') << f->fieldSize;
                out << std::dec << "\n";
            }
        }

        out << "\n// Total fields: " << data.fieldTable.size() << "\n";

        // Generate a compact lookup table for easy copy-paste.
        out << "\n// ═══ Field Offset Lookup Table ═══\n";
        out << "// Format: FIELD_OFFSET(Type, FieldName) → 0xNNNN\n\n";

        for (const auto& [typeName, fields] : byType) {
            std::string shortType = truncate(extractClassName(typeName), 30);
            for (const FieldEntry* f : fields) {
                out << "#define FIELD_OFFSET_" << sanitizeDefine(typeName)
                    << "_" << sanitizeDefine(f->name)
                    << " 0x" << std::hex << std::setw(4) << std::setfill('0') << f->offset
                    << std::dec << " // " << typeName << "::" << f->name << "\n";
            }
        }

        return out.str();
    }

    // Write static field report to file.
    static bool writeFile(const DumpData& data, const std::string& path) {
        std::ofstream f(path);
        if (!f.is_open()) return false;
        f << generate(data);
        return f.good();
    }

private:
    static std::string extractClassName(const std::string& fullName) {
        auto pos = fullName.rfind('.');
        return (pos != std::string::npos) ? fullName.substr(pos + 1) : fullName;
    }

    static std::string truncate(const std::string& s, size_t maxLen) {
        return (s.size() > maxLen) ? s.substr(0, maxLen) : s;
    }

    static std::string padRight(const std::string& s, size_t width) {
        if (s.size() >= width) return s;
        return s + std::string(width - s.size(), ' ');
    }

    static std::string sanitizeDefine(const std::string& name) {
        std::string r;
        r.reserve(name.size());
        for (char c : name) {
            if (std::isalnum(static_cast<unsigned char>(c)))
                r += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
            else
                r += '_';
        }
        return r;
    }
};

} // namespace omnibyte::dumper::dumper1
