#pragma once
// Dumper1 StructGenerator — generates struct layout definitions from DumpData.
// Produces C-style struct declarations with field offsets for reverse engineering.
#include "../../Dumper/DumperCore/DumpResult.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <map>

namespace omnibyte::dumper::dumper1 {

class StructGenerator {
public:
    // Generate struct definitions as string.
    static std::string generate(const DumpData& data) {
        std::ostringstream out;

        out << "// Generated by OmniByte Dumper1 — Struct Definitions\n";
        out << "// Engine: " << data.engineName << "\n";
        out << "// Types: " << data.typeTable.size() << "\n\n";
        out << "#pragma once\n";
        out << "#include <cstdint>\n";
        out << "#include <cstddef>\n\n";

        // Group types by namespace.
        std::map<std::string, std::vector<const TypeEntry*>> byNamespace;
        for (const auto& t : data.typeTable) {
            std::string ns = extractNamespace(t.name);
            byNamespace[ns].push_back(&t);
        }

        for (const auto& [ns, types] : byNamespace) {
            std::string nsTag = ns.empty() ? "Global" : ns;
            out << "// ── Namespace: " << nsTag << " ──\n";
            for (const TypeEntry* t : types) {
                writeStruct(out, *t, data);
            }
            out << "\n";
        }

        return out.str();
    }

    // Write struct definitions to file.
    static bool writeFile(const DumpData& data, const std::string& path) {
        std::ofstream f(path);
        if (!f.is_open()) return false;
        f << generate(data);
        return f.good();
    }

private:
    static std::string extractNamespace(const std::string& fullName) {
        auto pos = fullName.rfind('.');
        return (pos != std::string::npos) ? fullName.substr(0, pos) : "";
    }

    static std::string extractClassName(const std::string& fullName) {
        auto pos = fullName.rfind('.');
        return (pos != std::string::npos) ? fullName.substr(pos + 1) : fullName;
    }

    static std::string sanitize(const std::string& name) {
        std::string r;
        r.reserve(name.size());
        for (char c : name) {
            if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
                r += c;
            else
                r += '_';
        }
        return r;
    }

    static void writeStruct(std::ostringstream& out, const TypeEntry& type,
                            const DumpData& data) {
        std::string clsName = sanitize(extractClassName(type.name));

        // Collect fields for this type.
        std::vector<const FieldEntry*> fields;
        for (const auto& f : data.fieldTable) {
            if (f.declaringType == type.name) {
                fields.push_back(&f);
            }
        }

        // Sort by offset.
        std::sort(fields.begin(), fields.end(),
                  [](const FieldEntry* a, const FieldEntry* b) {
                      return a->offset < b->offset;
                  });

        out << "struct " << clsName;
        if (!type.parentType.empty()) {
            out << " : public " << sanitize(extractClassName(type.parentType));
        }
        out << " {\n";

        size_t currentOffset = 0;
        for (const FieldEntry* f : fields) {
            // Add padding if there's a gap.
            if (f->offset > currentOffset) {
                size_t padding = f->offset - currentOffset;
                out << "    uint8_t _pad" << std::dec << currentOffset
                    << "[0x" << std::hex << padding << "]; // padding\n";
            }

            std::string cType = mapToCType(f->typeName);
            out << "    " << cType << " " << sanitize(f->name);
            out << "; // 0x" << std::hex << std::setw(4) << std::setfill('0') << f->offset;
            if (f->fieldSize > 0) {
                out << " (size: 0x" << f->fieldSize << ")";
            }
            out << std::dec << "\n";

            currentOffset = f->offset + (f->fieldSize > 0 ? f->fieldSize : 4);
        }

        // Add tail padding comment if needed.
        if (type.size > 0 && currentOffset < type.size) {
            out << "    // Total size: 0x" << std::hex << type.size << std::dec << "\n";
        }

        out << "}; // sizeof(" << clsName << ") == 0x"
            << std::hex << (type.size > 0 ? type.size : currentOffset)
            << std::dec << "\n\n";
    }

    // Map IL2CPP type names to C/C++ types.
    static std::string mapToCType(const std::string& t) {
        if (t == "System.Boolean") return "bool";
        if (t == "System.Byte") return "uint8_t";
        if (t == "System.SByte") return "int8_t";
        if (t == "System.Int16") return "int16_t";
        if (t == "System.UInt16") return "uint16_t";
        if (t == "System.Int32") return "int32_t";
        if (t == "System.UInt32") return "uint32_t";
        if (t == "System.Int64") return "int64_t";
        if (t == "System.UInt64") return "uint64_t";
        if (t == "System.Single") return "float";
        if (t == "System.Double") return "double";
        if (t == "System.IntPtr") return "uintptr_t";
        if (t == "System.UIntPtr") return "uintptr_t";
        if (t == "System.String") return "uintptr_t"; // IL2CPP string is pointer
        if (t == "System.Void") return "void";
        if (t.find("System.Void*") != std::string::npos) return "void*";
        if (t.find('*') != std::string::npos) return "uintptr_t";
        if (t.empty()) return "uint8_t";
        // Unknown types → opaque bytes.
        return "uint8_t";
    }
};

} // namespace omnibyte::dumper::dumper1
