#pragma once
// HeaderWriter — Generates C/C++ struct declarations from DumpResult.
// Output format: C headers with structs, fields, padding, and size comments.
#include "../ExportCore/IExporter/IExporter.h"
#include "../ExportCore/SectionSplitter/SectionSplitter.h"
#include "../../DumperCore/DumpResult.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <set>

namespace omnibyte::dumper::writers {

class HeaderWriter : public export_core::IExporter {
public:
    std::string formatName() const override { return "header"; }
    std::string fileExtension() const override { return ".h"; }
    std::string description() const override {
        return "C/C++ struct declarations with offsets";
    }

    bool exportToFile(const DumpResult& result,
                      const std::string& outputPath) const override {
        std::ofstream file(outputPath);
        if (!file.is_open()) return false;

        file << exportToString(result);
        return file.good();
    }

    std::string exportToString(const DumpResult& result) const override {
        std::ostringstream out;

        // Header guard
        out << "#pragma once\n";
        out << "// Generated by OmniByte Dumper\n";
        out << "// Engine: " << result.engineName << " v" << result.detectedVersion << "\n";
        out << "// Types: " << result.typeTable.size() << "\n\n";

        out << "#include <stdint.h>\n";
        out << "#include <stddef.h>\n\n";

        // Forward declarations
        std::set<std::string> declaredTypes;
        for (const auto& type : result.typeTable) {
            std::string safeName = sanitizeName(type.name);
            if (declaredTypes.find(safeName) == declaredTypes.end()) {
                out << "struct " << safeName << ";\n";
                declaredTypes.insert(safeName);
            }
        }
        out << "\n";

        // Structs
        for (const auto& type : result.typeTable) {
            writeStruct(out, type, result);
        }

        return out.str();
    }

private:
    void writeStruct(std::ostringstream& out, const TypeEntry& type,
                     const DumpResult& result) const {
        std::string safeName = sanitizeName(type.name);

        out << "// Size: 0x" << std::hex << std::setw(4) << std::setfill('0') << type.size << "\n";
        if (!type.parentType.empty()) {
            out << "// Inherits: " << type.parentType << "\n";
        }
        out << "struct " << safeName << " {\n";

        // Get fields sorted by offset
        auto fields = export_core::SectionSplitter::getFieldsForType(result, type.name);

        uint64_t currentOffset = 0;
        for (size_t i = 0; i < fields.size(); ++i) {
            const auto& field = fields[i];

            // Add padding if there's a gap
            if (field.offset > currentOffset) {
                size_t padSize = field.offset - currentOffset;
                out << "    uint8_t _pad" << i << "[0x" << std::hex << padSize << "]; // 0x"
                    << std::setw(4) << std::setfill('0') << currentOffset << "\n";
            }

            // Field declaration
            std::string cType = mapToCType(field.typeName);
            out << "    " << cType << " " << field.name << "; // 0x"
                << std::setw(4) << std::setfill('0') << field.offset << "\n";

            currentOffset = field.offset + field.fieldSize;
        }

        // Pad to struct size
        if (currentOffset < type.size && type.size > 0) {
            size_t tailPad = type.size - currentOffset;
            out << "    uint8_t _tailPad[0x" << std::hex << tailPad << "];\n";
        }

        out << "};  // size: 0x" << std::hex << type.size << "\n\n";
    }

    static std::string mapToCType(const std::string& typeName) {
        // Map common types to C equivalents
        if (typeName == "bool") return "uint8_t";
        if (typeName == "int8_t" || typeName == "sbyte") return "int8_t";
        if (typeName == "uint8_t" || typeName == "byte") return "uint8_t";
        if (typeName == "int16_t" || typeName == "short") return "int16_t";
        if (typeName == "uint16_t" || typeName == "ushort") return "uint16_t";
        if (typeName == "int32_t" || typeName == "int") return "int32_t";
        if (typeName == "uint32_t" || typeName == "uint") return "uint32_t";
        if (typeName == "int64_t" || typeName == "long") return "int64_t";
        if (typeName == "uint64_t" || typeName == "ulong") return "uint64_t";
        if (typeName == "float") return "float";
        if (typeName == "double") return "double";
        if (typeName == "void*") return "void*";
        // Pointer types (FString, TArray, etc.)
        if (typeName.find('*') != std::string::npos) return "void*";
        return "void*"; // Default to void* for unknown types
    }

    static std::string sanitizeName(const std::string& name) {
        std::string result;
        result.reserve(name.size());
        for (char c : name) {
            if (c == '.') result += '_';
            else if (std::isalnum(c) || c == '_') result += c;
        }
        return result;
    }
};

} // namespace omnibyte::dumper::writers
